name: release.yml
on:
  push:
    tags:
      - '*'

jobs:
  tests:
    name: tests
    uses: ./.github/workflows/tests.yml

  build:
    name: Build distribution
    runs-on: ubuntu-latest
    needs: tests
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"
      - name: Install dependencies
        run: make install-ci
      - name: Build package
        run: make build
      - name: Store the distribution packages
        uses: actions/upload-artifact@v4
        with:
          name: packages-${{ github.ref_name }}
          path: dist/*

  release:
    name: Release to PyPI
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/project/${{ github.repository }}
    permissions:
      id-token: write
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: packages-${{ github.ref_name }}
          path: dist/
      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}

  github-release:
    name: Create release on Github
    needs: release
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: packages-${{ github.ref_name }}
          path: dist/
      - name: Create new release
        continue-on-error: true
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          body: |
            What's changed:
              * TODO

            Get it [here](https://pypi.org/project/${{ github.repository }}/${{ github.ref_name }})
          draft: true
